version: '3'
volumes:
  mediapirate_data:
  jellyfin_config:
  jellyfin_cache:
  transmission_config:
  prowlarr_config:
  sonarr_config:
  lidarr_config:
  radarr_config:
  readarr_config:
  jellyseerr_config:

services:
  #---------------------------------------------------------------------#
  #     Homarr - A simple, yet powerful dashboard for your server.      #
  #---------------------------------------------------------------------#
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - mediapirate_data:/app/data/homarr
    ports:
      - '7575:7575'
    networks:
      - mediapirate_net

  #---------------------------------------------------------------------#
  #     Jellyfin - The Free Software Media System                       #
  #---------------------------------------------------------------------#
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: 'unless-stopped'
    user: uid:gid
    ports:
      - '8096:8096'
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - mediapirate_data:/media

  #---------------------------------------------------------------------#
  #     Transmission - A Fast, Easy and Free BitTorrent Client          #
  #---------------------------------------------------------------------#
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - transmission_config:/config
      - mediapirate_data:/downloads
      - mediapirate_data:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - mediapirate_net

  #---------------------------------------------------------------------#
  #     Prowlarr - Indexer Manager/Proxy built on the *arr .net         #
  #---------------------------------------------------------------------#
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr_config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - mediapirate_net

  #---------------------------------------------------------------------#
  #     Sonarr - Smart PVR for Newsgroup and BitTorrent Users           #
  #---------------------------------------------------------------------#
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - sonarr_config:/config
      - mediapirate_data:/tv
      - mediapirate_data:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - mediapirate_net

  #---------------------------------------------------------------------#
  #     Lidarr - Music Collection Manager for Usenet and BitTorrent     #
  #---------------------------------------------------------------------#
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - lidarr_config:/config
      - mediapirate_data:/music
      - mediapirate_data:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
    networks:
      - mediapirate_net

  #---------------------------------------------------------------------#
  #     Radarr - A fork of Sonarr to work with movies                   #
  #---------------------------------------------------------------------#
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - radarr_config:/config
      - mediapirate_data:/movies
      - mediapirate_data:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - mediapirate_net

  #---------------------------------------------------------------------#
  #     Readarr - Book Collection Manager for Usenet and BitTorrent     #
  #---------------------------------------------------------------------#
  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - readarr_config:/config
      - mediapirate_data:/books
      - mediapirate_data:/downloads
    ports:
      - 8787:8787
    restart: unless-stopped
    networks:
      - mediapirate_net

  #---------------------------------------------------------------------#
  #     Jellyseerr - Movie & TV Show Request Manager for Jellyfin       #
  #---------------------------------------------------------------------#
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Asia/Tashkent
    ports:
      - 5055:5055
    volumes:
      - jellyseerr_config:/app/config
    restart: unless-stopped
    networks:
      - mediapirate_net

networks:
  mediapirate_net:
